"""Temporarily make admin_id nullable for dev testing

Revision ID: 062230c8c7b2
Revises: eb836ccf8df3
Create Date: 2025-08-28 04:22:36.208096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '062230c8c7b2'
down_revision: Union[str, None] = 'eb836ccf8df3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parents', 'admin_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('teachers', 'admin_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teachers', 'admin_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('parents', 'admin_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
