"""Add foreign key constraints to analytics report

Revision ID: 32bed9c60b97
Revises: e2a4bcea1015
Create Date: 2025-08-21 21:32:43.634775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32bed9c60b97'
down_revision: Union[str, None] = 'e2a4bcea1015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Table is empty so we can safely drop and recreate the student_id column
    try:
        op.drop_index('ix_analytics_reports_student_id', table_name='analytics_reports')
    except Exception:
        # index may not exist; ignore
        pass
    try:
        op.drop_column('analytics_reports', 'student_id')
    except Exception:
        pass
    op.add_column('analytics_reports', sa.Column('student_id', sa.dialects.postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'analytics_reports', 'term_weeks', ['week_id'], ['week_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'analytics_reports', 'teachers', ['teacher_id'], ['teacher_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'analytics_reports', 'students', ['student_id'], ['student_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'analytics_reports', 'academic_terms', ['term_id'], ['term_id'], ondelete='CASCADE')
    op.drop_column('parent_student_links', 'relationship_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent_student_links', sa.Column('relationship_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'analytics_reports', type_='foreignkey')
    op.drop_constraint(None, 'analytics_reports', type_='foreignkey')
    op.drop_constraint(None, 'analytics_reports', type_='foreignkey')
    op.drop_constraint(None, 'analytics_reports', type_='foreignkey')
    op.create_index('ix_analytics_reports_student_id', 'analytics_reports', ['student_id'], unique=False)
    op.alter_column('analytics_reports', 'student_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
