"""Remove rating column from students table

Revision ID: 35cb834e593a
Revises: f134be83a308
Create Date: 2025-09-07 02:30:53.866226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35cb834e593a'
down_revision: Union[str, None] = 'f134be83a308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_student_rating', table_name='students')
    op.drop_column('students', 'rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('rating', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.create_index('ix_student_rating', 'students', ['rating'], unique=False)
    # ### end Alembic commands ###
