"""make student.admin_id nullable

Revision ID: 608c08e59c3d
Revises: 32bed9c60b97
Create Date: 2025-08-22 02:49:34.498972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '608c08e59c3d'
down_revision: Union[str, None] = '32bed9c60b97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # keep analytics_reports.student_id type as UUID (no type change)
    op.create_index('ix_analytics_student_report_date', 'analytics_reports', ['student_id', 'report_date'], unique=False)
    op.alter_column('students', 'admin_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'admin_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('ix_analytics_student_report_date', table_name='analytics_reports')
    # ### end Alembic commands ###
