"""Add teacher_ratings table

Revision ID: 784e48394735
Revises: 35cb834e593a
Create Date: 2025-09-08 04:24:31.886759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '784e48394735'
down_revision: Union[str, None] = '35cb834e593a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_ratings',
    sa.Column('rating_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('classroom_id', sa.UUID(), nullable=False),
    sa.Column('rating_points', sa.Integer(), nullable=False),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.classroom_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['academic_terms.term_id'], ),
    sa.PrimaryKeyConstraint('rating_id')
    )
    op.create_index('ix_teacher_rating_classroom_id', 'teacher_ratings', ['classroom_id'], unique=False)
    op.create_index('ix_teacher_rating_student_id', 'teacher_ratings', ['student_id'], unique=False)
    op.create_index('ix_teacher_rating_teacher_id', 'teacher_ratings', ['teacher_id'], unique=False)
    op.create_index('ix_teacher_rating_term_id', 'teacher_ratings', ['term_id'], unique=False)
    op.create_index('ix_teacher_rating_unique', 'teacher_ratings', ['teacher_id', 'student_id', 'classroom_id'], unique=True)
    op.create_index(op.f('ix_teacher_ratings_classroom_id'), 'teacher_ratings', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_teacher_ratings_rating_id'), 'teacher_ratings', ['rating_id'], unique=True)
    op.create_index(op.f('ix_teacher_ratings_student_id'), 'teacher_ratings', ['student_id'], unique=False)
    op.create_index(op.f('ix_teacher_ratings_teacher_id'), 'teacher_ratings', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_teacher_ratings_term_id'), 'teacher_ratings', ['term_id'], unique=False)
    op.drop_table('lesson_vectors')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_vectors',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['lesson_chunks.chunk_id'], name='lesson_vectors_chunk_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='lesson_vectors_pkey')
    )
    op.drop_index(op.f('ix_teacher_ratings_term_id'), table_name='teacher_ratings')
    op.drop_index(op.f('ix_teacher_ratings_teacher_id'), table_name='teacher_ratings')
    op.drop_index(op.f('ix_teacher_ratings_student_id'), table_name='teacher_ratings')
    op.drop_index(op.f('ix_teacher_ratings_rating_id'), table_name='teacher_ratings')
    op.drop_index(op.f('ix_teacher_ratings_classroom_id'), table_name='teacher_ratings')
    op.drop_index('ix_teacher_rating_unique', table_name='teacher_ratings')
    op.drop_index('ix_teacher_rating_term_id', table_name='teacher_ratings')
    op.drop_index('ix_teacher_rating_teacher_id', table_name='teacher_ratings')
    op.drop_index('ix_teacher_rating_student_id', table_name='teacher_ratings')
    op.drop_index('ix_teacher_rating_classroom_id', table_name='teacher_ratings')
    op.drop_table('teacher_ratings')
    # ### end Alembic commands ###
