"""Add tables

Revision ID: 89e16440d0f8
Revises: 7c707dca9184
Create Date: 2025-08-18 03:28:17.881497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89e16440d0f8'
down_revision: Union[str, None] = '7c707dca9184'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_terms',
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('term_id')
    )
    op.create_index('ix_academic_term_end_date', 'academic_terms', ['end_date'], unique=False)
    op.create_index('ix_academic_term_name', 'academic_terms', ['name'], unique=False)
    op.create_index('ix_academic_term_start_date', 'academic_terms', ['start_date'], unique=False)
    op.create_index(op.f('ix_academic_terms_term_id'), 'academic_terms', ['term_id'], unique=True)
    op.create_table('admins',
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_index('ix_admin_email', 'admins', ['email'], unique=False)
    op.create_index(op.f('ix_admins_admin_id'), 'admins', ['admin_id'], unique=True)
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_table('analytics_reports',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('teacher_id', sa.UUID(), nullable=True),
    sa.Column('week_id', sa.UUID(), nullable=True),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index('ix_analytics_report_date', 'analytics_reports', ['report_date'], unique=False)
    op.create_index(op.f('ix_analytics_reports_report_id'), 'analytics_reports', ['report_id'], unique=True)
    op.create_index(op.f('ix_analytics_reports_student_id'), 'analytics_reports', ['student_id'], unique=False)
    op.create_index(op.f('ix_analytics_reports_teacher_id'), 'analytics_reports', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_analytics_reports_term_id'), 'analytics_reports', ['term_id'], unique=False)
    op.create_index(op.f('ix_analytics_reports_week_id'), 'analytics_reports', ['week_id'], unique=False)
    op.create_index('ix_analytics_student_report_date', 'analytics_reports', ['student_id', 'report_date'], unique=False)
    op.create_index('ix_analytics_teacher_report_date', 'analytics_reports', ['teacher_id', 'report_date'], unique=False)
    op.create_table('subjects',
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('subject_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_subject_name', 'subjects', ['name'], unique=False)
    op.create_index(op.f('ix_subjects_subject_id'), 'subjects', ['subject_id'], unique=True)
    op.create_table('parents',
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.admin_id'], ),
    sa.PrimaryKeyConstraint('parent_id')
    )
    op.create_index('ix_parent_email', 'parents', ['email'], unique=False)
    op.create_index(op.f('ix_parents_admin_id'), 'parents', ['admin_id'], unique=False)
    op.create_index(op.f('ix_parents_email'), 'parents', ['email'], unique=True)
    op.create_index(op.f('ix_parents_parent_id'), 'parents', ['parent_id'], unique=True)
    op.create_table('teachers',
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.DECIMAL(), nullable=True),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('term_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.admin_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['academic_terms.term_id'], ),
    sa.PrimaryKeyConstraint('teacher_id')
    )
    op.create_index('ix_teacher_email', 'teachers', ['email'], unique=False)
    op.create_index('ix_teacher_rating', 'teachers', ['rating'], unique=False)
    op.create_index(op.f('ix_teachers_admin_id'), 'teachers', ['admin_id'], unique=False)
    op.create_index(op.f('ix_teachers_email'), 'teachers', ['email'], unique=True)
    op.create_index(op.f('ix_teachers_subject_id'), 'teachers', ['subject_id'], unique=False)
    op.create_index(op.f('ix_teachers_teacher_id'), 'teachers', ['teacher_id'], unique=True)
    op.create_index(op.f('ix_teachers_term_id'), 'teachers', ['term_id'], unique=False)
    op.create_table('term_weeks',
    sa.Column('week_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['term_id'], ['academic_terms.term_id'], ),
    sa.PrimaryKeyConstraint('week_id')
    )
    op.create_index('ix_term_week_term_id', 'term_weeks', ['term_id'], unique=False)
    op.create_index('ix_term_week_week_number', 'term_weeks', ['week_number'], unique=False)
    op.create_index(op.f('ix_term_weeks_term_id'), 'term_weeks', ['term_id'], unique=False)
    op.create_index(op.f('ix_term_weeks_week_id'), 'term_weeks', ['week_id'], unique=False)
    op.create_table('exams',
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['academic_terms.term_id'], ),
    sa.PrimaryKeyConstraint('exam_id')
    )
    op.create_index('ix_exam_teacher_date', 'exams', ['teacher_id', 'date'], unique=False)
    op.create_index('ix_exam_term_date', 'exams', ['term_id', 'date'], unique=False)
    op.create_index(op.f('ix_exams_exam_id'), 'exams', ['exam_id'], unique=True)
    op.create_index(op.f('ix_exams_teacher_id'), 'exams', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_exams_term_id'), 'exams', ['term_id'], unique=False)
    op.create_table('lessons',
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('pdf_url', sa.String(length=512), nullable=False),
    sa.Column('rating', sa.DECIMAL(), nullable=True),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['academic_terms.term_id'], ),
    sa.PrimaryKeyConstraint('lesson_id')
    )
    op.create_index('ix_lesson_subject_id', 'lessons', ['subject_id'], unique=False)
    op.create_index('ix_lesson_teacher_id', 'lessons', ['teacher_id'], unique=False)
    op.create_index('ix_lesson_term_id', 'lessons', ['term_id'], unique=False)
    op.create_index(op.f('ix_lessons_lesson_id'), 'lessons', ['lesson_id'], unique=True)
    op.create_index(op.f('ix_lessons_subject_id'), 'lessons', ['subject_id'], unique=False)
    op.create_index(op.f('ix_lessons_teacher_id'), 'lessons', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_lessons_term_id'), 'lessons', ['term_id'], unique=False)
    op.create_table('question_practices',
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='difficulty_enum'), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['academic_terms.term_id'], ),
    sa.PrimaryKeyConstraint('practice_id')
    )
    op.create_index('ix_question_practice_teacher_id', 'question_practices', ['teacher_id'], unique=False)
    op.create_index('ix_question_practice_term_id', 'question_practices', ['term_id'], unique=False)
    op.create_index(op.f('ix_question_practices_practice_id'), 'question_practices', ['practice_id'], unique=False)
    op.create_index(op.f('ix_question_practices_teacher_id'), 'question_practices', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_question_practices_term_id'), 'question_practices', ['term_id'], unique=False)
    op.create_table('students',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.DECIMAL(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('term_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.admin_id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.parent_id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['academic_terms.term_id'], ),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_index('ix_student_email', 'students', ['email'], unique=False)
    op.create_index('ix_student_rating', 'students', ['rating'], unique=False)
    op.create_index(op.f('ix_students_admin_id'), 'students', ['admin_id'], unique=False)
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=True)
    op.create_index(op.f('ix_students_parent_id'), 'students', ['parent_id'], unique=False)
    op.create_index(op.f('ix_students_student_id'), 'students', ['student_id'], unique=True)
    op.create_index(op.f('ix_students_term_id'), 'students', ['term_id'], unique=False)
    op.create_table('classrooms',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['academic_terms.term_id'], ),
    sa.PrimaryKeyConstraint('student_id', 'subject_id', 'teacher_id')
    )
    op.create_index('ix_classroom_student_subject', 'classrooms', ['student_id', 'subject_id'], unique=False)
    op.create_index('ix_classroom_teacher_subject', 'classrooms', ['teacher_id', 'subject_id'], unique=False)
    op.create_index('ix_classroom_term_id', 'classrooms', ['term_id'], unique=False)
    op.create_index(op.f('ix_classrooms_term_id'), 'classrooms', ['term_id'], unique=False)
    op.create_table('exam_results',
    sa.Column('result_id', sa.UUID(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.DECIMAL(), nullable=False),
    sa.Column('exam_rating', sa.DECIMAL(), nullable=True),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.exam_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['academic_terms.term_id'], ),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_index('ix_exam_result_exam_id', 'exam_results', ['exam_id'], unique=False)
    op.create_index('ix_exam_result_student_score', 'exam_results', ['student_id', 'score'], unique=False)
    op.create_index(op.f('ix_exam_results_exam_id'), 'exam_results', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_results_result_id'), 'exam_results', ['result_id'], unique=False)
    op.create_index(op.f('ix_exam_results_student_id'), 'exam_results', ['student_id'], unique=False)
    op.create_index(op.f('ix_exam_results_term_id'), 'exam_results', ['term_id'], unique=False)
    op.create_table('lesson_chunks',
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('chunk_number', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.lesson_id'], ),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_index('ix_lesson_chunk_lesson_id', 'lesson_chunks', ['lesson_id'], unique=False)
    op.create_index('ix_lesson_chunk_number', 'lesson_chunks', ['chunk_number'], unique=False)
    op.create_index(op.f('ix_lesson_chunks_chunk_id'), 'lesson_chunks', ['chunk_id'], unique=True)
    op.create_index(op.f('ix_lesson_chunks_lesson_id'), 'lesson_chunks', ['lesson_id'], unique=False)
    op.create_table('question_exams',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='difficulty_enum'), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.exam_id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['academic_terms.term_id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_index('ix_question_exam_exam_id', 'question_exams', ['exam_id'], unique=False)
    op.create_index('ix_question_exam_teacher_id', 'question_exams', ['teacher_id'], unique=False)
    op.create_index('ix_question_exam_term_id', 'question_exams', ['term_id'], unique=False)
    op.create_index(op.f('ix_question_exams_exam_id'), 'question_exams', ['exam_id'], unique=False)
    op.create_index(op.f('ix_question_exams_question_id'), 'question_exams', ['question_id'], unique=True)
    op.create_index(op.f('ix_question_exams_teacher_id'), 'question_exams', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_question_exams_term_id'), 'question_exams', ['term_id'], unique=False)
    op.create_table('answers',
    sa.Column('answer_id', sa.UUID(), nullable=False),
    sa.Column('question_practice_id', sa.UUID(), nullable=True),
    sa.Column('question_exam_id', sa.UUID(), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['question_exam_id'], ['question_exams.question_id'], ),
    sa.ForeignKeyConstraint(['question_practice_id'], ['question_practices.practice_id'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    op.create_index('ix_answer_question_exam_id', 'answers', ['question_exam_id'], unique=False)
    op.create_index('ix_answer_question_practice_id', 'answers', ['question_practice_id'], unique=False)
    op.create_index(op.f('ix_answers_answer_id'), 'answers', ['answer_id'], unique=True)
    op.create_index(op.f('ix_answers_question_exam_id'), 'answers', ['question_exam_id'], unique=False)
    op.create_index(op.f('ix_answers_question_practice_id'), 'answers', ['question_practice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answers_question_practice_id'), table_name='answers')
    op.drop_index(op.f('ix_answers_question_exam_id'), table_name='answers')
    op.drop_index(op.f('ix_answers_answer_id'), table_name='answers')
    op.drop_index('ix_answer_question_practice_id', table_name='answers')
    op.drop_index('ix_answer_question_exam_id', table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_question_exams_term_id'), table_name='question_exams')
    op.drop_index(op.f('ix_question_exams_teacher_id'), table_name='question_exams')
    op.drop_index(op.f('ix_question_exams_question_id'), table_name='question_exams')
    op.drop_index(op.f('ix_question_exams_exam_id'), table_name='question_exams')
    op.drop_index('ix_question_exam_term_id', table_name='question_exams')
    op.drop_index('ix_question_exam_teacher_id', table_name='question_exams')
    op.drop_index('ix_question_exam_exam_id', table_name='question_exams')
    op.drop_table('question_exams')
    op.drop_index(op.f('ix_lesson_chunks_lesson_id'), table_name='lesson_chunks')
    op.drop_index(op.f('ix_lesson_chunks_chunk_id'), table_name='lesson_chunks')
    op.drop_index('ix_lesson_chunk_number', table_name='lesson_chunks')
    op.drop_index('ix_lesson_chunk_lesson_id', table_name='lesson_chunks')
    op.drop_table('lesson_chunks')
    op.drop_index(op.f('ix_exam_results_term_id'), table_name='exam_results')
    op.drop_index(op.f('ix_exam_results_student_id'), table_name='exam_results')
    op.drop_index(op.f('ix_exam_results_result_id'), table_name='exam_results')
    op.drop_index(op.f('ix_exam_results_exam_id'), table_name='exam_results')
    op.drop_index('ix_exam_result_student_score', table_name='exam_results')
    op.drop_index('ix_exam_result_exam_id', table_name='exam_results')
    op.drop_table('exam_results')
    op.drop_index(op.f('ix_classrooms_term_id'), table_name='classrooms')
    op.drop_index('ix_classroom_term_id', table_name='classrooms')
    op.drop_index('ix_classroom_teacher_subject', table_name='classrooms')
    op.drop_index('ix_classroom_student_subject', table_name='classrooms')
    op.drop_table('classrooms')
    op.drop_index(op.f('ix_students_term_id'), table_name='students')
    op.drop_index(op.f('ix_students_student_id'), table_name='students')
    op.drop_index(op.f('ix_students_parent_id'), table_name='students')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_index(op.f('ix_students_admin_id'), table_name='students')
    op.drop_index('ix_student_rating', table_name='students')
    op.drop_index('ix_student_email', table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_question_practices_term_id'), table_name='question_practices')
    op.drop_index(op.f('ix_question_practices_teacher_id'), table_name='question_practices')
    op.drop_index(op.f('ix_question_practices_practice_id'), table_name='question_practices')
    op.drop_index('ix_question_practice_term_id', table_name='question_practices')
    op.drop_index('ix_question_practice_teacher_id', table_name='question_practices')
    op.drop_table('question_practices')
    op.drop_index(op.f('ix_lessons_term_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_teacher_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_subject_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_lesson_id'), table_name='lessons')
    op.drop_index('ix_lesson_term_id', table_name='lessons')
    op.drop_index('ix_lesson_teacher_id', table_name='lessons')
    op.drop_index('ix_lesson_subject_id', table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_exams_term_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_teacher_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_exam_id'), table_name='exams')
    op.drop_index('ix_exam_term_date', table_name='exams')
    op.drop_index('ix_exam_teacher_date', table_name='exams')
    op.drop_table('exams')
    op.drop_index(op.f('ix_term_weeks_week_id'), table_name='term_weeks')
    op.drop_index(op.f('ix_term_weeks_term_id'), table_name='term_weeks')
    op.drop_index('ix_term_week_week_number', table_name='term_weeks')
    op.drop_index('ix_term_week_term_id', table_name='term_weeks')
    op.drop_table('term_weeks')
    op.drop_index(op.f('ix_teachers_term_id'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_teacher_id'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_subject_id'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_email'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_admin_id'), table_name='teachers')
    op.drop_index('ix_teacher_rating', table_name='teachers')
    op.drop_index('ix_teacher_email', table_name='teachers')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_parents_parent_id'), table_name='parents')
    op.drop_index(op.f('ix_parents_email'), table_name='parents')
    op.drop_index(op.f('ix_parents_admin_id'), table_name='parents')
    op.drop_index('ix_parent_email', table_name='parents')
    op.drop_table('parents')
    op.drop_index(op.f('ix_subjects_subject_id'), table_name='subjects')
    op.drop_index('ix_subject_name', table_name='subjects')
    op.drop_table('subjects')
    op.drop_index('ix_analytics_teacher_report_date', table_name='analytics_reports')
    op.drop_index('ix_analytics_student_report_date', table_name='analytics_reports')
    op.drop_index(op.f('ix_analytics_reports_week_id'), table_name='analytics_reports')
    op.drop_index(op.f('ix_analytics_reports_term_id'), table_name='analytics_reports')
    op.drop_index(op.f('ix_analytics_reports_teacher_id'), table_name='analytics_reports')
    op.drop_index(op.f('ix_analytics_reports_student_id'), table_name='analytics_reports')
    op.drop_index(op.f('ix_analytics_reports_report_id'), table_name='analytics_reports')
    op.drop_index('ix_analytics_report_date', table_name='analytics_reports')
    op.drop_table('analytics_reports')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_index(op.f('ix_admins_admin_id'), table_name='admins')
    op.drop_index('ix_admin_email', table_name='admins')
    op.drop_table('admins')
    op.drop_index(op.f('ix_academic_terms_term_id'), table_name='academic_terms')
    op.drop_index('ix_academic_term_start_date', table_name='academic_terms')
    op.drop_index('ix_academic_term_name', table_name='academic_terms')
    op.drop_index('ix_academic_term_end_date', table_name='academic_terms')
    op.drop_table('academic_terms')
    # ### end Alembic commands ###
