"""Add celery_task_executions table

Revision ID: 9b3f6a2c4d1e
Revises: e7761be0525c
Create Date: 2025-08-25 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b3f6a2c4d1e'
down_revision: Union[str, None] = 'e7761be0525c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'celery_task_executions',
        sa.Column('execution_id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('task_name', sa.String(length=255), nullable=False),
        sa.Column('task_args_hash', sa.String(length=64), nullable=False),
        sa.Column('celery_task_id', postgresql.UUID(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False, server_default=sa.text("'PENDING'")),
        sa.Column('task_args', postgresql.JSONB(), nullable=True),
        sa.Column('result', postgresql.JSONB(), nullable=True),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('execution_id')
    )

    op.create_index('ixz_task_name_args_celery_hash', 'celery_task_executions', ['task_name', 'task_args_hash', 'celery_task_id'], unique=True)
    op.create_index('ixz_task_execution_status', 'celery_task_executions', ['status'], unique=False)
    op.create_index('ixz_task_execution_started_at', 'celery_task_executions', ['started_at'], unique=False)
    op.create_index('ixz_task_execution_completed_at', 'celery_task_executions', ['completed_at'], unique=False)
    op.create_index('ixz_celery_task_id', 'celery_task_executions', ['celery_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ixz_celery_task_id', table_name='celery_task_executions')
    op.drop_index('ixz_task_execution_completed_at', table_name='celery_task_executions')
    op.drop_index('ixz_task_execution_started_at', table_name='celery_task_executions')
    op.drop_index('ixz_task_execution_status', table_name='celery_task_executions')
    op.drop_index('ixz_task_name_args_celery_hash', table_name='celery_task_executions')
    op.drop_table('celery_task_executions')
    # ### end Alembic commands ###
