"""refactor_user_models_with_unique_ids

Revision ID: e2a4bcea1015
Revises: 89e16440d0f8
Create Date: 2025-08-19 22:22:12.303896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2a4bcea1015'
down_revision: Union[str, None] = '89e16440d0f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent_student_links',
    sa.Column('link_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.parent_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('link_id')
    )
    op.create_index('ix_parent_student_active', 'parent_student_links', ['parent_id', 'student_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_parent_student_links_link_id'), 'parent_student_links', ['link_id'], unique=False)
    op.create_index(op.f('ix_parent_student_links_parent_id'), 'parent_student_links', ['parent_id'], unique=False)
    op.create_index(op.f('ix_parent_student_links_student_id'), 'parent_student_links', ['student_id'], unique=False)
    op.create_index('ix_parent_student_unique', 'parent_student_links', ['parent_id', 'student_id'], unique=True)
    op.add_column('admins', sa.Column('unique_id', sa.String(length=20), nullable=False))
    op.create_index('ix_admin_unique_id', 'admins', ['unique_id'], unique=False)
    op.create_index(op.f('ix_admins_unique_id'), 'admins', ['unique_id'], unique=True)
    op.add_column('parents', sa.Column('unique_id', sa.String(length=20), nullable=False))
    op.alter_column('parents', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('parents', 'admin_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index('ix_parent_unique_id', 'parents', ['unique_id'], unique=False)
    op.create_index(op.f('ix_parents_unique_id'), 'parents', ['unique_id'], unique=True)
    op.add_column('students', sa.Column('unique_id', sa.String(length=20), nullable=False))
    op.alter_column('students', 'admin_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('ix_students_parent_id', table_name='students')
    op.create_index('ix_student_unique_id', 'students', ['unique_id'], unique=False)
    op.create_index(op.f('ix_students_unique_id'), 'students', ['unique_id'], unique=True)
    op.drop_constraint('students_parent_id_fkey', 'students', type_='foreignkey')
    op.drop_column('students', 'parent_id')
    op.add_column('teachers', sa.Column('unique_id', sa.String(length=20), nullable=False))
    op.alter_column('teachers', 'admin_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index('ix_teacher_unique_id', 'teachers', ['unique_id'], unique=False)
    op.create_index(op.f('ix_teachers_unique_id'), 'teachers', ['unique_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teachers_unique_id'), table_name='teachers')
    op.drop_index('ix_teacher_unique_id', table_name='teachers')
    op.alter_column('teachers', 'admin_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('teachers', 'unique_id')
    op.add_column('students', sa.Column('parent_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('students_parent_id_fkey', 'students', 'parents', ['parent_id'], ['parent_id'])
    op.drop_index(op.f('ix_students_unique_id'), table_name='students')
    op.drop_index('ix_student_unique_id', table_name='students')
    op.create_index('ix_students_parent_id', 'students', ['parent_id'], unique=False)
    op.alter_column('students', 'admin_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('students', 'unique_id')
    op.drop_index(op.f('ix_parents_unique_id'), table_name='parents')
    op.drop_index('ix_parent_unique_id', table_name='parents')
    op.alter_column('parents', 'admin_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('parents', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('parents', 'unique_id')
    op.drop_index(op.f('ix_admins_unique_id'), table_name='admins')
    op.drop_index('ix_admin_unique_id', table_name='admins')
    op.drop_column('admins', 'unique_id')
    op.drop_index('ix_parent_student_unique', table_name='parent_student_links')
    op.drop_index(op.f('ix_parent_student_links_student_id'), table_name='parent_student_links')
    op.drop_index(op.f('ix_parent_student_links_parent_id'), table_name='parent_student_links')
    op.drop_index(op.f('ix_parent_student_links_link_id'), table_name='parent_student_links')
    op.drop_index('ix_parent_student_active', table_name='parent_student_links')
    op.drop_table('parent_student_links')
    # ### end Alembic commands ###
