"""Fix analytics and subjects schema

Revision ID: eb836ccf8df3
Revises: 1279f9f021f5
Create Date: 2025-08-27 04:35:34.899046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb836ccf8df3'
down_revision: Union[str, None] = '1279f9f021f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ixz_celery_task_id', table_name='celery_task_executions')
    op.drop_index('ixz_task_execution_completed_at', table_name='celery_task_executions')
    op.drop_index('ixz_task_execution_started_at', table_name='celery_task_executions')
    op.drop_index('ixz_task_execution_status', table_name='celery_task_executions')
    op.drop_index('ixz_task_name_args_celery_hash', table_name='celery_task_executions')
    op.drop_table('celery_task_executions')
    op.alter_column('analytics_reports', 'student_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_analytics_reports_student_id'), 'analytics_reports', ['student_id'], unique=False)
    op.drop_constraint('analytics_reports_student_id_fkey', 'analytics_reports', type_='foreignkey')
    op.drop_constraint('analytics_reports_teacher_id_fkey', 'analytics_reports', type_='foreignkey')
    op.drop_constraint('analytics_reports_week_id_fkey', 'analytics_reports', type_='foreignkey')
    op.drop_constraint('analytics_reports_term_id_fkey', 'analytics_reports', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('analytics_reports_term_id_fkey', 'analytics_reports', 'academic_terms', ['term_id'], ['term_id'], ondelete='CASCADE')
    op.create_foreign_key('analytics_reports_week_id_fkey', 'analytics_reports', 'term_weeks', ['week_id'], ['week_id'], ondelete='SET NULL')
    op.create_foreign_key('analytics_reports_teacher_id_fkey', 'analytics_reports', 'teachers', ['teacher_id'], ['teacher_id'], ondelete='SET NULL')
    op.create_foreign_key('analytics_reports_student_id_fkey', 'analytics_reports', 'students', ['student_id'], ['student_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_analytics_reports_student_id'), table_name='analytics_reports')
    op.alter_column('analytics_reports', 'student_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_table('celery_task_executions',
    sa.Column('execution_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('task_args_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('celery_task_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=False),
    sa.Column('task_args', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('execution_id', name='celery_task_executions_pkey')
    )
    op.create_index('ixz_task_name_args_celery_hash', 'celery_task_executions', ['task_name', 'task_args_hash', 'celery_task_id'], unique=True)
    op.create_index('ixz_task_execution_status', 'celery_task_executions', ['status'], unique=False)
    op.create_index('ixz_task_execution_started_at', 'celery_task_executions', ['started_at'], unique=False)
    op.create_index('ixz_task_execution_completed_at', 'celery_task_executions', ['completed_at'], unique=False)
    op.create_index('ixz_celery_task_id', 'celery_task_executions', ['celery_task_id'], unique=False)
    # ### end Alembic commands ###
