"""Add student response models

Revision ID: f134be83a308
Revises: f78097be0ccd
Create Date: 2025-09-06 21:24:51.579033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f134be83a308'
down_revision: Union[str, None] = 'f78097be0ccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_ratings',
    sa.Column('rating_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('practice_questions_answered', sa.Integer(), nullable=False),
    sa.Column('practice_questions_correct', sa.Integer(), nullable=False),
    sa.Column('practice_accuracy_rate', sa.DECIMAL(precision=5, scale=4), nullable=False),
    sa.Column('exams_taken', sa.Integer(), nullable=False),
    sa.Column('total_exam_score', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('average_exam_score', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('overall_rating', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['academic_terms.term_id'], ),
    sa.PrimaryKeyConstraint('rating_id')
    )
    op.create_index('ix_student_rating_overall', 'student_ratings', ['overall_rating'], unique=False)
    op.create_index('ix_student_rating_student_id', 'student_ratings', ['student_id'], unique=False)
    op.create_index('ix_student_rating_term_id', 'student_ratings', ['term_id'], unique=False)
    op.create_index('ix_student_rating_unique', 'student_ratings', ['student_id', 'term_id'], unique=True)
    op.create_index(op.f('ix_student_ratings_rating_id'), 'student_ratings', ['rating_id'], unique=False)
    op.create_index(op.f('ix_student_ratings_student_id'), 'student_ratings', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_ratings_term_id'), 'student_ratings', ['term_id'], unique=False)
    op.create_table('exam_question_responses',
    sa.Column('response_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('answer_id', sa.UUID(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.answer_id'], ),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.exam_id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question_exams.question_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('response_id')
    )
    op.create_index(op.f('ix_exam_question_responses_answer_id'), 'exam_question_responses', ['answer_id'], unique=False)
    op.create_index(op.f('ix_exam_question_responses_exam_id'), 'exam_question_responses', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_question_responses_question_id'), 'exam_question_responses', ['question_id'], unique=False)
    op.create_index(op.f('ix_exam_question_responses_response_id'), 'exam_question_responses', ['response_id'], unique=False)
    op.create_index(op.f('ix_exam_question_responses_student_id'), 'exam_question_responses', ['student_id'], unique=False)
    op.create_index('ix_exam_response_answered_at', 'exam_question_responses', ['answered_at'], unique=False)
    op.create_index('ix_exam_response_exam_id', 'exam_question_responses', ['exam_id'], unique=False)
    op.create_index('ix_exam_response_question_id', 'exam_question_responses', ['question_id'], unique=False)
    op.create_index('ix_exam_response_student_id', 'exam_question_responses', ['student_id'], unique=False)
    op.create_index('ix_exam_response_unique', 'exam_question_responses', ['student_id', 'question_id'], unique=True)
    op.create_table('practice_question_responses',
    sa.Column('response_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('answer_id', sa.UUID(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.answer_id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['question_practices.practice_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('response_id')
    )
    op.create_index(op.f('ix_practice_question_responses_answer_id'), 'practice_question_responses', ['answer_id'], unique=False)
    op.create_index(op.f('ix_practice_question_responses_practice_id'), 'practice_question_responses', ['practice_id'], unique=False)
    op.create_index(op.f('ix_practice_question_responses_response_id'), 'practice_question_responses', ['response_id'], unique=False)
    op.create_index(op.f('ix_practice_question_responses_student_id'), 'practice_question_responses', ['student_id'], unique=False)
    op.create_index('ix_practice_response_answered_at', 'practice_question_responses', ['answered_at'], unique=False)
    op.create_index('ix_practice_response_practice_id', 'practice_question_responses', ['practice_id'], unique=False)
    op.create_index('ix_practice_response_student_id', 'practice_question_responses', ['student_id'], unique=False)
    op.create_index('ix_practice_response_unique', 'practice_question_responses', ['student_id', 'practice_id'], unique=True)
    op.drop_index('ixz_celery_task_id', table_name='celery_task_executions')
    op.drop_index('ixz_task_execution_completed_at', table_name='celery_task_executions')
    op.drop_index('ixz_task_execution_started_at', table_name='celery_task_executions')
    op.drop_index('ixz_task_execution_status', table_name='celery_task_executions')
    op.drop_index('ixz_task_name_args_celery_hash', table_name='celery_task_executions')
    op.drop_table('celery_task_executions')
    op.create_index('ix_classroom_term_id', 'classrooms', ['term_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_classroom_term_id', table_name='classrooms')
    op.create_table('celery_task_executions',
    sa.Column('execution_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('task_args_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('celery_task_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=False),
    sa.Column('task_args', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('execution_id', name='celery_task_executions_pkey')
    )
    op.create_index('ixz_task_name_args_celery_hash', 'celery_task_executions', ['task_name', 'task_args_hash', 'celery_task_id'], unique=True)
    op.create_index('ixz_task_execution_status', 'celery_task_executions', ['status'], unique=False)
    op.create_index('ixz_task_execution_started_at', 'celery_task_executions', ['started_at'], unique=False)
    op.create_index('ixz_task_execution_completed_at', 'celery_task_executions', ['completed_at'], unique=False)
    op.create_index('ixz_celery_task_id', 'celery_task_executions', ['celery_task_id'], unique=False)
    op.drop_index('ix_practice_response_unique', table_name='practice_question_responses')
    op.drop_index('ix_practice_response_student_id', table_name='practice_question_responses')
    op.drop_index('ix_practice_response_practice_id', table_name='practice_question_responses')
    op.drop_index('ix_practice_response_answered_at', table_name='practice_question_responses')
    op.drop_index(op.f('ix_practice_question_responses_student_id'), table_name='practice_question_responses')
    op.drop_index(op.f('ix_practice_question_responses_response_id'), table_name='practice_question_responses')
    op.drop_index(op.f('ix_practice_question_responses_practice_id'), table_name='practice_question_responses')
    op.drop_index(op.f('ix_practice_question_responses_answer_id'), table_name='practice_question_responses')
    op.drop_table('practice_question_responses')
    op.drop_index('ix_exam_response_unique', table_name='exam_question_responses')
    op.drop_index('ix_exam_response_student_id', table_name='exam_question_responses')
    op.drop_index('ix_exam_response_question_id', table_name='exam_question_responses')
    op.drop_index('ix_exam_response_exam_id', table_name='exam_question_responses')
    op.drop_index('ix_exam_response_answered_at', table_name='exam_question_responses')
    op.drop_index(op.f('ix_exam_question_responses_student_id'), table_name='exam_question_responses')
    op.drop_index(op.f('ix_exam_question_responses_response_id'), table_name='exam_question_responses')
    op.drop_index(op.f('ix_exam_question_responses_question_id'), table_name='exam_question_responses')
    op.drop_index(op.f('ix_exam_question_responses_exam_id'), table_name='exam_question_responses')
    op.drop_index(op.f('ix_exam_question_responses_answer_id'), table_name='exam_question_responses')
    op.drop_table('exam_question_responses')
    op.drop_index(op.f('ix_student_ratings_term_id'), table_name='student_ratings')
    op.drop_index(op.f('ix_student_ratings_student_id'), table_name='student_ratings')
    op.drop_index(op.f('ix_student_ratings_rating_id'), table_name='student_ratings')
    op.drop_index('ix_student_rating_unique', table_name='student_ratings')
    op.drop_index('ix_student_rating_term_id', table_name='student_ratings')
    op.drop_index('ix_student_rating_student_id', table_name='student_ratings')
    op.drop_index('ix_student_rating_overall', table_name='student_ratings')
    op.drop_table('student_ratings')
    # ### end Alembic commands ###
