"""Update classroom table structure for two-step workflow

Revision ID: f78097be0ccd
Revises: 062230c8c7b2
Create Date: 2025-09-01 00:37:17.331118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f78097be0ccd'
down_revision: Union[str, None] = '062230c8c7b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Step 1: Create a temporary new classrooms table with the correct structure
    op.create_table('classrooms_new',
        sa.Column('classroom_id', sa.UUID(), nullable=False, primary_key=True),
        sa.Column('subject_id', sa.UUID(), nullable=False),
        sa.Column('teacher_id', sa.UUID(), nullable=False), 
        sa.Column('term_id', sa.UUID(), nullable=False),
        sa.Column('grade_level', sa.String(length=10), nullable=False),
        sa.Column('classroom_name', sa.String(length=100), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
        sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ),
        sa.ForeignKeyConstraint(['term_id'], ['academic_terms.term_id'], ),
        sa.PrimaryKeyConstraint('classroom_id')
    )
    
    # Step 2: Drop old indexes that will conflict
    op.drop_index('ix_classroom_student_subject', table_name='classrooms', if_exists=True)
    op.drop_index('ix_classroom_teacher_subject', table_name='classrooms', if_exists=True)
    
    # Step 3: Drop the old classrooms table
    op.drop_table('classrooms')
    
    # Step 4: Rename the new table to 'classrooms'
    op.rename_table('classrooms_new', 'classrooms')
    
    # Step 5: Create indexes for the new classrooms table
    op.create_index('ix_classroom_grade_level', 'classrooms', ['grade_level'], unique=False)
    op.create_index('ix_classroom_subject_teacher', 'classrooms', ['subject_id', 'teacher_id'], unique=False)
    op.create_index('ix_classroom_unique_setup', 'classrooms', ['subject_id', 'teacher_id', 'term_id', 'grade_level'], unique=True)
    op.create_index(op.f('ix_classrooms_classroom_id'), 'classrooms', ['classroom_id'], unique=True)
    op.create_index(op.f('ix_classrooms_classroom_name'), 'classrooms', ['classroom_name'], unique=False)
    op.create_index(op.f('ix_classrooms_grade_level'), 'classrooms', ['grade_level'], unique=False)
    op.create_index(op.f('ix_classrooms_subject_id'), 'classrooms', ['subject_id'], unique=False)
    op.create_index(op.f('ix_classrooms_teacher_id'), 'classrooms', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_classrooms_term_id'), 'classrooms', ['term_id'], unique=False)
    
    # Step 6: Create the classroom_students association table
    op.create_table('classroom_students',
    sa.Column('classroom_student_id', sa.UUID(), nullable=False),
    sa.Column('classroom_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.classroom_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('classroom_student_id')
    )
    op.create_index('ix_classroom_student_unique', 'classroom_students', ['classroom_id', 'student_id'], unique=True)
    op.create_index('ix_classroom_students_classroom', 'classroom_students', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_classroom_students_classroom_id'), 'classroom_students', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_classroom_students_classroom_student_id'), 'classroom_students', ['classroom_student_id'], unique=True)
    op.create_index('ix_classroom_students_student', 'classroom_students', ['student_id'], unique=False)
    op.create_index(op.f('ix_classroom_students_student_id'), 'classroom_students', ['student_id'], unique=False)
    
    # Clean up old tables if they exist (optional cleanup)
    op.drop_table('lesson_vectors', if_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classrooms', sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('classrooms_student_id_fkey', 'classrooms', 'students', ['student_id'], ['student_id'])
    op.drop_index(op.f('ix_classrooms_teacher_id'), table_name='classrooms')
    op.drop_index(op.f('ix_classrooms_subject_id'), table_name='classrooms')
    op.drop_index(op.f('ix_classrooms_grade_level'), table_name='classrooms')
    op.drop_index(op.f('ix_classrooms_classroom_name'), table_name='classrooms')
    op.drop_index(op.f('ix_classrooms_classroom_id'), table_name='classrooms')
    op.drop_index('ix_classroom_unique_setup', table_name='classrooms')
    op.drop_index('ix_classroom_subject_teacher', table_name='classrooms')
    op.drop_index('ix_classroom_grade_level', table_name='classrooms')
    op.create_index('ix_classroom_teacher_subject', 'classrooms', ['teacher_id', 'subject_id'], unique=False)
    op.create_index('ix_classroom_student_subject', 'classrooms', ['student_id', 'subject_id'], unique=False)
    op.drop_column('classrooms', 'classroom_name')
    op.drop_column('classrooms', 'grade_level')
    op.drop_column('classrooms', 'classroom_id')
    op.create_table('lesson_vectors',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['lesson_chunks.chunk_id'], name='lesson_vectors_chunk_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='lesson_vectors_pkey')
    )
    op.create_table('celery_task_executions',
    sa.Column('execution_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('task_args_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('celery_task_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=False),
    sa.Column('task_args', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('execution_id', name='celery_task_executions_pkey')
    )
    op.create_index('ixz_task_name_args_celery_hash', 'celery_task_executions', ['task_name', 'task_args_hash', 'celery_task_id'], unique=True)
    op.create_index('ixz_task_execution_status', 'celery_task_executions', ['status'], unique=False)
    op.create_index('ixz_task_execution_started_at', 'celery_task_executions', ['started_at'], unique=False)
    op.create_index('ixz_task_execution_completed_at', 'celery_task_executions', ['completed_at'], unique=False)
    op.create_index('ixz_celery_task_id', 'celery_task_executions', ['celery_task_id'], unique=False)
    op.drop_index(op.f('ix_classroom_students_student_id'), table_name='classroom_students')
    op.drop_index('ix_classroom_students_student', table_name='classroom_students')
    op.drop_index(op.f('ix_classroom_students_classroom_student_id'), table_name='classroom_students')
    op.drop_index(op.f('ix_classroom_students_classroom_id'), table_name='classroom_students')
    op.drop_index('ix_classroom_students_classroom', table_name='classroom_students')
    op.drop_index('ix_classroom_student_unique', table_name='classroom_students')
    op.drop_table('classroom_students')
    # ### end Alembic commands ###
